#cloud-config
users:
  - name: jtpereyda
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-import-id: lp:jtpereyda
package_upgrade: true
packages:
  - git
  - vim
  - tmux
  - wireshark
  - bc
  - python
  - python-pip
runcmd:
  - sudo -H -u jtpereyda git clone https://github.com/jtpereyda/dotfiles.git ~/dotfiles
  - sudo -H -u jtpereyda bash ~/dotfiles/ubuntu-spinup.sh
  - sudo -H -u jtpereyda bash ~/dotfiles/makesymlinks.sh

